### ISSUE TITLE
Add an example for UWP

### ISSUE THREAD

**Issue by SychevIgor** [Azure/azure-mobile-engagement-samples#10]
Add an example for UWP. When Microsoft talking about UWP, but not all sdks and services are available for UWP- it looks odd.

**Comment by SychevIgor** [comment]
https://feedback.azure.com/forums/285737-mobile-engagement/suggestions/11658654-uwp-samples-for-mobile-engagement

**Comment by piyushjo** [comment]
We do not have support for Cordova plugin for UWP yet. It is on our backlog though.

**Comment by piyushjo** [comment]
And we will add ready getting started sample for UWP in the samples folder.
