### ISSUE TITLE
AzureMobile Engagement Objective-C Sources

### ISSUE THREAD

**Issue by loretoparisi** [Azure/azure-mobile-engagement-samples#11]
I have seen that neither in this repo or in [Get Started with Azure Mobile Engagement for iOS apps in Objective C](https://azure.microsoft.com/en-us/documentation/articles/mobile-engagement-ios-get-started/) there are full sources of the Azure Mobile Engagement SDK. Only static library and partial sources are provided.
For other Azure sdk, like Messaging all sources are available, that help SDK integrators to have bitcode support and slice removing.
Is there anyway to get full sources of this sdk then?

**Comment by piyushjo** [comment]
Thank you for your comments. The SDK isn't open sourced yet. We will add it to our backlog.

**Comment by loretoparisi** [comment]
@piyushjo you definitively should, since it's very hard to handle it in a app iOS / watchOS / tvOS, ecc.
