### ISSUE TITLE
Feature request: Bitcode Support

### ISSUE THREAD

**Issue by loretoparisi** [Azure/azure-mobile-engagement-samples#14]
Since iOS 9 there is need of bitcode support by 3rdParty library, as requested by Apple.
Could you please provide bitcode support when archiving this project?

Thank you.

NOTE. This issue is related to the source code request: https://github.com/Azure/azure-mobile-engagement-samples/issues/11, since having the sources, this will not be a problem.

**Comment by iamclement** [comment]
Bitcode is enabled in the SDK since its version 3.2.0: https://azure.microsoft.com/documentation/articles/mobile-engagement-ios-release-notes/
The sample from this repo is integrating an old version of the SDK.

**Comment by loretoparisi** [comment]
Will this work when doing "Archive..." as well (that is not the same as just enabling bitcode)?

**Comment by loretoparisi** [comment]
Hi,
so I have checked the library for version 3.2.2 available from the download link here: https://azure.microsoft.com/it-it/documentation/articles/mobile-engagement-ios-get-started/

``` shell
macbookproloreto:EngagementSDK admin$ ls -l
total 4616
drwxr-xr-x@ 4 admin  staff      136  7 Apr 10:15 Classes
drwxr-xr-x@ 8 admin  staff      272  7 Apr 10:15 Headers
-rw-r--r--@ 1 admin  staff  2361328  7 Apr 10:15 libengagement.a
macbookproloreto:EngagementSDK admin$ otool -l libengagement.a | grep __LLVM
```

and 

``` shell
macbookproloreto:mobileengagement 2 admin$ cd EngagementReach/
macbookproloreto:EngagementReach admin$ ls -l
total 2832
drwxr-xr-x@ 23 admin  staff      782  7 Apr 10:15 Headers
-rw-r--r--@  1 admin  staff  1449432  7 Apr 10:15 libreach.a
drwxr-xr-x@  6 admin  staff      204  6 Apr 10:52 res
macbookproloreto:EngagementReach admin$ otool -l libreach.a | grep __LLVM
```

I cannot see any LLVM segment there, so there is no bitcode actually.

Where bitcode segments are there, the static library should show at least those segments

``` shell
macbookproloreto:SpotifySDK admin$ otool -l Spotify.a | grep __LLVM
   segname __LLVM
   segname __LLVM
   segname __LLVM
   segname __LLVM
```

Thank you.

**Comment by iamclement** [comment]
You are right, it's enabled but not embedded. A work item has been created to remediate.

**Comment by loretoparisi** [comment]
@clpolet 👍

**Comment by loretoparisi** [comment]
@cipolet Any update on the bitcode status for the "Archive" phase?

Thank you.

**Comment by iamclement** [comment]
I let @piyushjo answer the question.

**Comment by piyushjo** [comment]
Hi @loretoparisi , we are not prioritizing this issue right now so it is still in our backlog.

**Comment by loretoparisi** [comment]
@piyushjo Ok thanks, just consider that `bitcode` support is a requirement (not a desiderata) from Apple since `iOS9` and `iOS10` is shipping in October. 
Providing the sources, as for the other Azure SDK we are using as iOS libraries, will easily let the developers to handle this accordingly to their library needs.
Thank you.

**Comment by piyushjo** [comment]
Hi @loretoparisi , from the iOS documentation, looks like it is default but it is still an optional setting and not yet mandatory. 
https://developer.apple.com/library/watchos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html 
thank you for your feedback!

**Comment by loretoparisi** [comment]
Yes @piyushjo formally that is true, but consider two things
- Every frameworks built in the app must have `ENABLE BITCODE` set to true, otherwise the app cannot enable bitcode;
- Without bitcode enabled you are going to miss several features, among the others the binary optimization on the device: only with bitcode you will get app thinning `slicing` to work properly, and this is very important for app developers;
- The bitcode is required when you have `watchOS` and `tvOS` apps as we do:

> Note: For iOS apps, bitcode is the default, but optional. For watchOS and tvOS apps, bitcode is required. If you provide bitcode, all apps and frameworks in the app bundle (all targets in the project) need to include bitcode.

This means that, now, we cannot run built-in framework on `watchOS` apps due to some frameworks missing the bitcode.

We have embraced the bitcode features since the first very release supporting it and of course I understand that there are several issues connected to this, like under the hood C libraries that cannot be converted - like for audio streaming libraries, but if that is not the case, that is definitively a requirements to have an iOS app fully compliant to new guidelines for  app distribution on AppStore.

**Comment by loretoparisi** [comment]
Please take a look at Apple's forums interesting threads about bitcode
- [Bitcode and Assembly?](https://forums.developer.apple.com/message/11344#11344)
- [How to detect a library if it's contain bitcode?](https://forums.developer.apple.com/message/62669#62669)
- [Re: Bitcode in a static library requiremnts](https://forums.developer.apple.com/message/53542#53542)

**Comment by goneale** [comment]
I'm also waiting on this one desperately!

**Comment by loretoparisi** [comment]
💯

**Comment by jimmaye** [comment]
Would also love to see it enabled and embedded!

**Comment by iamclement** [comment]
https://github.com/Azure/azure-mobile-engagement-app-android/pull/5
