### ISSUE TITLE
App Crashes when initializing EngagementAgent

### ISSUE THREAD

**Issue by MobiDev-001** [Azure/azure-mobile-engagement-samples#17]
This line :
`[EngagementAgent init:kConnectionString];`
Causes this bug :
> Uncaught exception: *** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array

Any ideas what i'm doing wrong ?
P.S. : it was working just fine before I upgraded the SDK files to the latest version.

**Comment by iamclement** [comment]
https://github.com/Azure/azure-mobile-engagement-app-android/pull/5
